name: Build Binary Artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get .

      # Windows Cross-Compile Builds
      - name: Build for windows/amd64
        run: |
            env GOOS=windows GOARCH=amd64 
            go build -v -o git-ignit-windows-amd64.exe

      # Linux Builds
      # TODO

      # macOS Cross-Compile Builds?
      # TODO

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Test & Binary artifacts
          path: |
            git-ignit-windows-amd64.exe
